[package]
name = "prehnite"
description = "Writing support software that helps you create coherent sentences"
build = "build.rs"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true

[workspace]
members = ["build-libs", "core", "core/proc-macros"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Zlib"
authors = ["saku-shirakura<saku@sakushira.com>"]
repository = "https://github.com/saku-shirakura/prehnite"
homepage = "https://prehnite.jp/"
rust-version = "1.92"
publish = false

[features]
default = ["desktop"]

release = ["bundle_license"]
bundle_license = ["prehnite-build-libs/bundle_license"]
desktop = ["dioxus/desktop"]

[dependencies]
prehnite-core.workspace = true
tracing.workspace = true
tokio.workspace = true
sqlx.workspace = true
fluent-bundle.workspace = true
opener.workspace = true
anyhow.workspace = true
tracing-unwrap.workspace = true
thiserror.workspace = true
indexmap.workspace = true
dioxus.workspace = true
dioxus-desktop.workspace = true
dioxus-i18n.workspace = true
easy-settings.workspace = true
serde.workspace = true
chrono.workspace = true
sys-locale.workspace = true
serde_json.workspace = true
native-dialog.workspace = true
fallible-iterator.workspace = true

[workspace.dependencies]
prehnite-core = { version = "0.1.0", path = "core" }
chrono = { version = "0.4", features = ["serde"] }
sqlx = { version = "0.8", features = ["runtime-tokio", "sqlite", "chrono", "macros"] }
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros", "sync", "fs"] }
native-dialog = { version = "0.9", features = ["async"] }
serde = { version = "1", features = ["derive"] }
rhai = { version = "1", features = ["serde"] }
reqwest = { version = "0.13", features = ["json"] }
log = "0.4"
tracing-subscriber = { version = "0.3", features = ["chrono", "env-filter"] }
fluent-bundle = "0.16"
unic-langid = { version = "0.9", features = ["unic-langid-macros"] }
paste = "1"
derive_more = { version = "2", features = ["eq"] }
sys-locale = "0.3"
fluent-syntax = "0.12"
tracing = { version = "0.1", features = ["log"] }
tracing-appender = "0.2"
serde_json = "1"
zip = "8"
opener = "0.8"
anyhow = "1"
thiserror = "2"
tracing-unwrap = "1"
strum = { version = "0.28", features = ["derive"] }
indexmap = { version = "2", features = ["serde"] }
syn = { version = "2", features = ["full", "extra-traits"] }
proc-macro2 = "1"
quote = "1"
structmeta = "0.3.0"
convert_case = "0.11.0"
easy-settings = "0.2.2"
dioxus-i18n = "0.5"
dioxus = { version = "0.7", features = ["router"] }
dioxus-desktop = "0.7"
fallible-iterator = "0.3.0"

[build-dependencies]
prehnite-build-libs = { version = "0.1.0", path = "build-libs" }
anyhow.workspace = true
