[package]
name = "prehnite"
description = "Writing support software that helps you create coherent sentences"
build = "build.rs"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true
#categories.workspace = true
#keywords.workspace = true

[workspace]
members = ["core"]

[workspace.package]
version = "0.0.2-alpha"
edition = "2024"
license = "Zlib"
authors = ["saku-shirakura<saku@sakushira.com>"]
repository = "https://github.com/saku-shirakura/prehnite"
homepage = "https://prehnite.jp/"
rust-version = "1.92"
#categories = ["text-editors"]
#keywords = ["gui", "text-editors"]

[dependencies]
prehnite-core.workspace = true
iced.workspace = true
tracing.workspace = true
tokio.workspace = true
sqlx.workspace = true
native-dialog.workspace = true

[workspace.dependencies]
prehnite-core = { version = "0.0.2-alpha", path = "core" }
chrono = "0.4"
iced = { version = "0.14", features = ["tokio"] }
sqlx = { version = "0.8", features = ["runtime-tokio", "sqlite", "chrono", "macros"] }
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros", "sync"] }
native-dialog = { version = "0.9", features = ["async"] }
serde = { version = "1", features = ["derive"] }
rhai = { version = "1", features = ["serde"] }
reqwest = { version = "0.13", features = ["json"] }
log = "0.4"
tracing-subscriber = { version = "0.3", features = ["chrono", "env-filter"] }
fluent-bundle = "0.16"
unic-langid = { version = "0.9", features = ["unic-langid-macros"] }
paste = "1"
derive_more = { version = "2", features = ["eq"] }
sys-locale = "0.3.2"
fluent-syntax = "0.12"
tracing = { version = "0.1", features = ["log"] }
tracing-appender = "0.2"

[target.'cfg(windows)'.build-dependencies]
embed-resource = "3.0"
