[package]
name = "prehnite"
version = "0.1.0"
edition = "2024"
license = "Zlib"
authors = ["saku-shirakura<saku@sakushira.com>"]
description = "Coming soon"
repository = "https://github.com/saku-shirakura/prehnite"
homepage = "https://prehnite.jp/"
build = "build.rs"

[dependencies]
chrono = "0.4"
iced = { version = "0.14", features = ["tokio"] }
iced_aw = "0.13"
sqlx = { version = "0.8", features = ["runtime-tokio", "sqlite", "chrono"] }
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros"] }
native-dialog = { version = "0.9", features = ["async"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rhai = { version = "1", features = ["serde"] }
reqwest = { version = "0.12", features = ["json"] }
log = "0.4"
tracing-subscriber = "0.3"
fluent = "0.17.0"

[target.'cfg(windows)'.build-dependencies]
embed-resource = "3.0.6"
