[package]
name = "prehnite-core"
description = "Prehnite backend implementation"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true
publish.workspace = true

[features]

debug = []

[dependencies]
chrono.workspace = true
sqlx.workspace = true
tokio.workspace = true
native-dialog.workspace = true
serde.workspace = true
rhai.workspace = true
reqwest.workspace = true
log.workspace = true
tracing-subscriber.workspace = true
fluent-bundle.workspace = true
unic-langid.workspace = true
paste.workspace = true
derive_more.workspace = true
sys-locale.workspace = true
fluent-syntax.workspace = true
tracing.workspace = true
tracing-appender.workspace = true
iced.workspace = true
zip.workspace = true
prehnite-license-bundle.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing-unwrap.workspace = true

[dev-dependencies]
rand = "0.10"
