// AUTOGENERATED Components module
pub mod tabs;
pub mod accordion;
pub mod badge;
pub mod switch;
pub mod select;
pub mod tooltip;
pub mod separator;
pub mod input;
pub mod card;
pub mod label;
pub mod sheet;
pub mod button;
