// AUTOGENERATED Components module
pub mod tabs;
pub mod accordion;
pub mod badge;
pub mod switch;
pub mod select;
pub mod tooltip;
pub mod separator;
pub mod input;
pub mod card;
pub mod label;
pub mod sheet;
pub mod button;
pub mod scroll_area;
pub mod toggle_group;
pub mod toggle;
pub mod drag_and_drop_list;
