[package]
name = "prehnite-builder"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true
publish.workspace = true

[target.'cfg(windows)'.build-dependencies]
embed-resource = "3.0"

[dependencies]
krates = "0.20"
cargo-about = "0.8"
toml = "1"
serde.workspace = true
serde_json.workspace = true
spdx = "0.13"
reqwest = { version = "=0.12.28", features = ["blocking"] }
