[package]
name = "prehnite-build-libs"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true
publish.workspace = true

[features]
bundle_license = ["dep:cargo-about", "dep:krates", "dep:ureq"]

[dependencies]
cargo-about = { version = "0.9", optional = true }
krates = { version = "0.21", optional = true }
serde_json.workspace = true
ureq = { version = "3", optional = true }
zip.workspace = true
anyhow.workspace = true
prehnite-core.workspace = true
