name: cargo-deny
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: EmbarkStudios/cargo-deny-action@v2
        with:
          rust-version: 1.92
