name: CI
on:
  push:
    paths:
      - .github/workflows/ci.yml
      - Cargo.toml
      - Cargo.lock
      - '**/assets/**'
      - '**/migrations/**'
      - '**.rs'
      - '**.ftl'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      matrix:
        #        os: [ ubuntu-latest, windows-latest, macos-latest ]
        os: [ windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            . -> target
            core -> target
            build-libs -> target
      - name: Install dioxus-cli
        uses: taiki-e/install-action@v2.85.6
        with:
          tool: dioxus-cli@0.7.6
      - name: Dioxus Check
        run: dx check
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --workspace --verbose