name: CI
on:
  push:
    paths:
      - ci.yml
      - Cargo.toml
      - Cargo.lock
      - '**/assets/**'
      - '**/migrations/**'
      - '**.rs'
      - '**.ftl'
  pull_request:
    paths:
      - ci.yml
      - Cargo.toml
      - Cargo.lock
      - '**/assets/**'
      - '**/migrations/**'
      - '**.rs'
      - '**.ftl'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            . -> target
            core -> target
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --workspace --verbose